//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace languagetool_msword10_addin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("languagetool_msword10_addin.Resources.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asturian.
        /// </summary>
        internal static string ast_ES {
            get {
                return ResourceManager.GetString("ast_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        internal static string be_BY {
            get {
                return ResourceManager.GetString("be_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breton.
        /// </summary>
        internal static string br_FR {
            get {
                return ResourceManager.GetString("br_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        internal static string ca_ES {
            get {
                return ResourceManager.GetString("ca_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan (Valencian).
        /// </summary>
        internal static string ca_ES_valencia {
            get {
                return ResourceManager.GetString("ca_ES_valencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Options.
        /// </summary>
        internal static string checking_options {
            get {
                return ResourceManager.GetString("checking_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        internal static string da_DK {
            get {
                return ResourceManager.GetString("da_DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Austrian).
        /// </summary>
        internal static string de_AT {
            get {
                return ResourceManager.GetString("de_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Swiss).
        /// </summary>
        internal static string de_CH {
            get {
                return ResourceManager.GetString("de_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Germany).
        /// </summary>
        internal static string de_DE {
            get {
                return ResourceManager.GetString("de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (Easy German).
        /// </summary>
        internal static string de_DE_x_simple_language {
            get {
                return ResourceManager.GetString("de_DE_x_simple_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Language.
        /// </summary>
        internal static string default_language {
            get {
                return ResourceManager.GetString("default_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        internal static string el_GR {
            get {
                return ResourceManager.GetString("el_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Australian).
        /// </summary>
        internal static string en_AU {
            get {
                return ResourceManager.GetString("en_AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Canadian).
        /// </summary>
        internal static string en_CA {
            get {
                return ResourceManager.GetString("en_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (British).
        /// </summary>
        internal static string en_GB {
            get {
                return ResourceManager.GetString("en_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (New Zealand).
        /// </summary>
        internal static string en_NZ {
            get {
                return ResourceManager.GetString("en_NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (American).
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (South African).
        /// </summary>
        internal static string en_ZA {
            get {
                return ResourceManager.GetString("en_ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esperanto.
        /// </summary>
        internal static string eo {
            get {
                return ResourceManager.GetString("eo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galician.
        /// </summary>
        internal static string gl_ES {
            get {
                return ResourceManager.GetString("gl_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        internal static string grammar {
            get {
                return ResourceManager.GetString("grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string ignore_all {
            get {
                return ResourceManager.GetString("ignore_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Once.
        /// </summary>
        internal static string ignore_once {
            get {
                return ResourceManager.GetString("ignore_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        internal static string is_IS {
            get {
                return ResourceManager.GetString("is_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string ja_JP {
            get {
                return ResourceManager.GetString("ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khmer.
        /// </summary>
        internal static string km_KH {
            get {
                return ResourceManager.GetString("km_KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        internal static string lt_LT {
            get {
                return ResourceManager.GetString("lt_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageTool Server.
        /// </summary>
        internal static string LT_server {
            get {
                return ResourceManager.GetString("LT_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageTool Settings.
        /// </summary>
        internal static string LT_settings {
            get {
                return ResourceManager.GetString("LT_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malayalam.
        /// </summary>
        internal static string ml_IN {
            get {
                return ResourceManager.GetString("ml_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string more_information {
            get {
                return ResourceManager.GetString("more_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors were found..
        /// </summary>
        internal static string no_errors_found {
            get {
                return ResourceManager.GetString("no_errors_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string pl_PL {
            get {
                return ResourceManager.GetString("pl_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofreading with LanguageTool.
        /// </summary>
        internal static string proofreading_with_LanguageTool {
            get {
                return ResourceManager.GetString("proofreading_with_LanguageTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        internal static string pt_BR {
            get {
                return ResourceManager.GetString("pt_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Portugal).
        /// </summary>
        internal static string pt_PT {
            get {
                return ResourceManager.GetString("pt_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        internal static string ro_RO {
            get {
                return ResourceManager.GetString("ro_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string ru_RU {
            get {
                return ResourceManager.GetString("ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        internal static string sk_SK {
            get {
                return ResourceManager.GetString("sk_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        internal static string sl_SI {
            get {
                return ResourceManager.GetString("sl_SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling.
        /// </summary>
        internal static string spelling {
            get {
                return ResourceManager.GetString("spelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string suggestions {
            get {
                return ResourceManager.GetString("suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string sv {
            get {
                return ResourceManager.GetString("sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamil.
        /// </summary>
        internal static string ta_IN {
            get {
                return ResourceManager.GetString("ta_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalog.
        /// </summary>
        internal static string tl_PH {
            get {
                return ResourceManager.GetString("tl_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typography.
        /// </summary>
        internal static string typography {
            get {
                return ResourceManager.GetString("typography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string uk_UA {
            get {
                return ResourceManager.GetString("uk_UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server.
        /// </summary>
        internal static string unable_to_connect_to_server {
            get {
                return ResourceManager.GetString("unable_to_connect_to_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
    }
}
